# Spring Configuration  
spring :
  datasource :
    url : jdbc:mysql://mysql.cjhaycyxwtq4.ap-northeast-2.rds.amazonaws.com:3306/app_moim
    username : admin
    password : 1q2w3e4r
    driver-class-name : com.mysql.cj.jdbc.Driver